# Generated by Django 3.0.7 on 2020-06-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
    ]
