# Generated by Django 3.0.7 on 2020-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='steps',
            field=models.CharField(max_length=128),
        ),
    ]
