# Generated by Django 3.0.7 on 2020-06-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200610_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='counts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
