# Generated by Django 3.0.7 on 2020-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='red_line',
            field=models.CharField(default=None, max_length=48),
        ),
    ]
