# Generated by Django 3.0.7 on 2020-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_red_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='red_line',
            field=models.CharField(default='', max_length=48),
        ),
    ]
